apiVersion: appconfiguration.azure.upbound.io/v1beta1
kind: Configuration
metadata:
  annotations:
    meta.upbound.io/example-id: appconfiguration/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: appconftest
  name: appconftest
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: appconftestgrp
    name: appconftestname

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: appconfiguration/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: appconftestgrp
  name: appconftestgrp
spec:
  forProvider:
    location: West Europe