apiVersion: web.azure.upbound.io/v1beta1
kind: WindowsFunctionAppSlot
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/windowsfunctionappslot
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    functionAppIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    siteConfig:
    - {}
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: web.azure.upbound.io/v1beta1
kind: WindowsFunctionApp
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/windowsfunctionappslot
  labels:
    testing.upbound.io/example-name: example
  name: windowsfunctionappnameaa
spec:
  forProvider:
    location: East US
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    servicePlanIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    siteConfig:
      - {}
    storageAccountAccessKeySecretRef:
      key: example-key
      name: example-name
      namespace: upbound-system
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: v1
kind: Secret
metadata:
  name: example-name
  namespace: upbound-system
type: Opaque
data:
  example-key: "bXJ06E6nNnr/j4kemUlz2B/n4MqILTG9MwQdIuXY4gQmillkI7nt5heqaYEDXH2JV2DG4lwwpK86+ASt2+ta+Q=="

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/windowsfunctionappslot
  labels:
    testing.upbound.io/example-name: example
  name: windows-rg-aa
spec:
  forProvider:
    location: East US

---

apiVersion: web.azure.upbound.io/v1beta1
kind: ServicePlan
metadata:
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-windows-func-app.sh
    meta.upbound.io/example-id: web/v1beta1/windowsfunctionappslot
  labels:
    testing.upbound.io/example-name: example
  name: windows-sp-aa
spec:
  forProvider:
    location: East US
    osType: Windows
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: S1

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/windowsfunctionappslot
  labels:
    testing.upbound.io/example-name: example
  name: waccnameaa
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: East US
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example