apiVersion: authorization.azure.upbound.io/v1beta1
kind: ResourcePolicyAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1beta1/resourcepolicyassignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-policy-assignment
    policyDefinitionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceId: ${data.azurerm_virtual_network.example.id}

---

apiVersion: authorization.azure.upbound.io/v1beta1
kind: PolicyDefinition
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1beta1/resourcepolicyassignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    mode: All
    policyRule: "\t{\n    \"if\": {\n      \"not\": {\n        \"field\": \"location\",\n
      \       \"equals\": \"westeurope\"\n      }\n    },\n    \"then\": {\n      \"effect\":
      \"Deny\"\n    }\n  }\n"
    policyType: Custom

---

