apiVersion: signalrservice.azure.upbound.io/v1beta1
kind: WebPubsub
metadata:
  annotations:
    meta.upbound.io/example-id: signalrservice/v1beta1/webpubsub
  labels:
    testing.upbound.io/example-name: example
  name: webpubsubname
spec:
  forProvider:
    capacity: 1
    identity:
    - type: SystemAssigned
    liveTrace:
    - connectivityLogsEnabled: false
      enabled: true
      messagingLogsEnabled: true
    location: West Europe
    publicNetworkAccessEnabled: false
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Standard_S1

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: signalrservice/v1beta1/webpubsub
  labels:
    testing.upbound.io/example-name: example
  name: web-rg
spec:
  forProvider:
    location: West Europe